-- =====================================================
-- Adaptive Learning Navigator
-- Schema aligned with current JPA entities
-- NOTE:
--   With spring.sql.init.mode=always this script recreates the dev schema
--   on every application start.
-- =====================================================

-- Drop in reverse dependency order
DROP TABLE IF EXISTS quiz_attempts;
DROP TABLE IF EXISTS quiz_options;
DROP TABLE IF EXISTS quiz_questions;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS topic_progress;
DROP TABLE IF EXISTS plan_step_explanation_prereqs;
DROP TABLE IF EXISTS plan_step_explanations;
DROP TABLE IF EXISTS plan_step_resources;
DROP TABLE IF EXISTS plan_steps;
DROP TABLE IF EXISTS plan_weeks;
DROP TABLE IF EXISTS plan_params_snapshots;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS user_known_topics;
DROP TABLE IF EXISTS topic_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS topic_resources;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS role_topics;
DROP TABLE IF EXISTS role_goals;
DROP TABLE IF EXISTS topic_prereqs;
DROP TABLE IF EXISTS user_preferred_resource_types;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_users_email ON users(email);

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY,
    preferred_language VARCHAR(10),
    hours_per_week_default INT,
    CONSTRAINT fk_user_preferences_user
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE user_preferred_resource_types (
    user_id BIGINT NOT NULL,
    resource_type VARCHAR(30) NOT NULL,
    PRIMARY KEY (user_id, resource_type),
    CONSTRAINT fk_user_pref_resource_types_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_user_pref_resource_type
        CHECK (resource_type IN ('VIDEO', 'ARTICLE', 'COURSE', 'BOOK', 'INTERACTIVE'))
);

CREATE TABLE topics (
    topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    level VARCHAR(20),
    is_core BOOLEAN NOT NULL,
    estimated_hours NUMERIC(6,2),
    status VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_topic_level
        CHECK (level IS NULL OR level IN ('BASIC', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT chk_topic_status
        CHECK (status IS NULL OR status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_topics_code ON topics(code);
CREATE INDEX idx_topics_status ON topics(status);

CREATE TABLE topic_prereqs (
    topic_prereq_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prereq_topic_id BIGINT NOT NULL,
    next_topic_id BIGINT NOT NULL,
    relation_type VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_topic_prereq_pair UNIQUE (prereq_topic_id, next_topic_id),
    CONSTRAINT fk_topic_prereqs_prereq
        FOREIGN KEY (prereq_topic_id) REFERENCES topics(topic_id),
    CONSTRAINT fk_topic_prereqs_next
        FOREIGN KEY (next_topic_id) REFERENCES topics(topic_id),
    CONSTRAINT chk_topic_prereq_relation
        CHECK (relation_type IS NULL OR relation_type IN ('REQUIRED', 'RECOMMENDED'))
);

CREATE INDEX idx_prereq_prereq ON topic_prereqs(prereq_topic_id);
CREATE INDEX idx_prereq_next ON topic_prereqs(next_topic_id);

CREATE TABLE role_goals (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(20),
    CONSTRAINT chk_role_goal_status
        CHECK (status IS NULL OR status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_role_goals_code ON role_goals(code);

CREATE TABLE role_topics (
    role_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    priority INT,
    is_required BOOLEAN NOT NULL,
    PRIMARY KEY (role_id, topic_id),
    CONSTRAINT fk_role_topics_role
        FOREIGN KEY (role_id) REFERENCES role_goals(role_id),
    CONSTRAINT fk_role_topics_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
);

CREATE TABLE resources (
    resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    type VARCHAR(30),
    language VARCHAR(10),
    duration_minutes INT,
    provider VARCHAR(120),
    difficulty VARCHAR(20),
    status VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_resource_type
        CHECK (type IS NULL OR type IN ('VIDEO', 'ARTICLE', 'COURSE', 'BOOK', 'INTERACTIVE')),
    CONSTRAINT chk_resource_status
        CHECK (status IS NULL OR status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_resources_type ON resources(type);
CREATE INDEX idx_resources_status ON resources(status);

CREATE TABLE topic_resources (
    topic_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    rank INT,
    PRIMARY KEY (topic_id, resource_id),
    CONSTRAINT fk_topic_resources_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id),
    CONSTRAINT fk_topic_resources_resource
        FOREIGN KEY (resource_id) REFERENCES resources(resource_id)
);

CREATE TABLE tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE
);

CREATE INDEX idx_tags_name ON tags(name);

CREATE TABLE topic_tags (
    topic_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (topic_id, tag_id),
    CONSTRAINT fk_topic_tags_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id),
    CONSTRAINT fk_topic_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags(tag_id)
);

CREATE TABLE user_known_topics (
    user_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    source VARCHAR(20),
    confidence NUMERIC(3,2),
    marked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (user_id, topic_id),
    CONSTRAINT fk_user_known_topics_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_known_topics_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id),
    CONSTRAINT chk_user_known_source
        CHECK (source IS NULL OR source IN ('MANUAL', 'QUIZ', 'IMPORT'))
);

CREATE TABLE plans (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    status VARCHAR(20),
    base_plan_id BIGINT,
    scenario_type VARCHAR(20),
    scenario_label VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_plans_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_plans_role
        FOREIGN KEY (role_id) REFERENCES role_goals(role_id),
    CONSTRAINT fk_plans_base_plan
        FOREIGN KEY (base_plan_id) REFERENCES plans(plan_id),
    CONSTRAINT chk_plan_scenario_type
        CHECK (scenario_type IS NULL OR scenario_type IN ('BASE', 'WHAT_IF'))
);

CREATE INDEX idx_plans_user ON plans(user_id);
CREATE INDEX idx_plans_role ON plans(role_id);
CREATE INDEX idx_plans_base ON plans(base_plan_id);

CREATE TABLE plan_params_snapshots (
    plan_id BIGINT PRIMARY KEY,
    hours_per_week INT NOT NULL,
    prefs_language VARCHAR(10),
    prefs_resource_types VARCHAR(200),
    algo_version VARCHAR(20) NOT NULL,
    CONSTRAINT fk_plan_params_snapshot_plan
        FOREIGN KEY (plan_id) REFERENCES plans(plan_id)
);

CREATE TABLE plan_weeks (
    plan_week_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    week_index INT NOT NULL,
    hours_budget NUMERIC(6,2) NOT NULL,
    hours_planned NUMERIC(6,2),
    CONSTRAINT uq_plan_week_index UNIQUE (plan_id, week_index),
    CONSTRAINT fk_plan_weeks_plan
        FOREIGN KEY (plan_id) REFERENCES plans(plan_id)
);

CREATE TABLE plan_steps (
    plan_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_week_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    order_in_week INT NOT NULL,
    planned_hours NUMERIC(6,2) NOT NULL,
    is_optional BOOLEAN NOT NULL,
    CONSTRAINT uq_step_week_order UNIQUE (plan_week_id, order_in_week),
    CONSTRAINT uq_step_week_topic UNIQUE (plan_week_id, topic_id),
    CONSTRAINT fk_plan_steps_week
        FOREIGN KEY (plan_week_id) REFERENCES plan_weeks(plan_week_id),
    CONSTRAINT fk_plan_steps_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
);

CREATE TABLE plan_step_resources (
    plan_step_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL,
    PRIMARY KEY (plan_step_id, resource_id),
    CONSTRAINT fk_plan_step_resources_step
        FOREIGN KEY (plan_step_id) REFERENCES plan_steps(plan_step_id),
    CONSTRAINT fk_plan_step_resources_resource
        FOREIGN KEY (resource_id) REFERENCES resources(resource_id)
);

CREATE TABLE plan_step_explanations (
    plan_step_id BIGINT PRIMARY KEY,
    rule_applied VARCHAR(80),
    topic_priority_reason VARCHAR(200),
    resource_reason VARCHAR(200),
    CONSTRAINT fk_plan_step_explanations_step
        FOREIGN KEY (plan_step_id) REFERENCES plan_steps(plan_step_id)
);

CREATE TABLE plan_step_explanation_prereqs (
    plan_step_id BIGINT NOT NULL,
    prereq_topic_id BIGINT NOT NULL,
    prereq_status VARCHAR(30),
    PRIMARY KEY (plan_step_id, prereq_topic_id),
    CONSTRAINT fk_plan_step_expl_prereq_explanation
        FOREIGN KEY (plan_step_id) REFERENCES plan_step_explanations(plan_step_id),
    CONSTRAINT fk_plan_step_expl_prereq_topic
        FOREIGN KEY (prereq_topic_id) REFERENCES topics(topic_id),
    CONSTRAINT chk_plan_step_prereq_status
        CHECK (prereq_status IS NULL OR prereq_status IN ('DONE', 'IN_PREVIOUS_STEPS', 'MISSING'))
);

CREATE TABLE topic_progress (
    plan_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (plan_id, topic_id),
    CONSTRAINT fk_topic_progress_plan
        FOREIGN KEY (plan_id) REFERENCES plans(plan_id),
    CONSTRAINT fk_topic_progress_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id),
    CONSTRAINT chk_topic_progress_status
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'DONE'))
);

CREATE TABLE quizzes (
    quiz_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    status VARCHAR(20),
    CONSTRAINT fk_quizzes_topic
        FOREIGN KEY (topic_id) REFERENCES topics(topic_id),
    CONSTRAINT chk_quiz_status
        CHECK (status IS NULL OR status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_quiz_topic ON quizzes(topic_id);

CREATE TABLE quiz_questions (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    type VARCHAR(20),
    order_index INT NOT NULL,
    CONSTRAINT fk_quiz_questions_quiz
        FOREIGN KEY (quiz_id) REFERENCES quizzes(quiz_id),
    CONSTRAINT chk_quiz_question_type
        CHECK (type IS NULL OR type IN ('SINGLE', 'MULTIPLE'))
);

CREATE INDEX idx_question_quiz ON quiz_questions(quiz_id);

CREATE TABLE quiz_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    CONSTRAINT fk_quiz_options_question
        FOREIGN KEY (question_id) REFERENCES quiz_questions(question_id)
);

CREATE INDEX idx_option_question ON quiz_options(question_id);

CREATE TABLE quiz_attempts (
    attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quiz_id BIGINT NOT NULL,
    score NUMERIC(5,2),
    correct_count INT,
    total_count INT,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_quiz_attempts_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_quiz_attempts_quiz
        FOREIGN KEY (quiz_id) REFERENCES quizzes(quiz_id)
);

CREATE INDEX idx_attempt_user ON quiz_attempts(user_id);
CREATE INDEX idx_attempt_quiz ON quiz_attempts(quiz_id);
